-- outdated schema


DELETE FROM Leaderboard;
DELETE FROM Problems;
DELETE FROM Users;

INSERT INTO Users (username, name) VALUES ('Madhanns', 'MADHANAGOPAL N S');
INSERT INTO Users (username, name) VALUES ('koushiksm445', 'S M Koushik');
INSERT INTO Users (username, name) VALUES ('hemcharan205', 'A Hemcharan');
INSERT INTO Users (username, name) VALUES ('jayesh56643', 'A Jayesh Ranjan');
INSERT INTO Users (username, name) VALUES ('Praful_Srinivasan_27', 'A Praful Srinivasan');
INSERT INTO Users (username, name) VALUES ('RvV3leSH7t', 'Rakesh Hiremath');
INSERT INTO Users (username, name) VALUES ('aish_02102006', 'A Y AISHWARYA');
INSERT INTO Users (username, name) VALUES ('abirami_0108', 'A. Abirami');
INSERT INTO Users (username, name) VALUES ('tansi_rani', 'A.Tansi Rani');
INSERT INTO Users (username, name) VALUES ('Aadhan27', 'AADHAN G P');
INSERT INTO Users (username, name) VALUES ('aadhyavballu', 'Aadhya V Ballu');
INSERT INTO Users (username, name) VALUES ('Aadya_u3770025', 'Aadya s sharma');
INSERT INTO Users (username, name) VALUES ('Aadyasha_2210', 'Aadyasha Samantaray');
INSERT INTO Users (username, name) VALUES ('aarohi_sharma', 'Aarohi Sharma');
INSERT INTO Users (username, name) VALUES ('Aari_2066', 'Aarushi Chaturvedi');
INSERT INTO Users (username, name) VALUES ('aashirwadaszns', 'Aashirwad Aanand');
INSERT INTO Users (username, name) VALUES ('aashutoshkrsah', 'Aashutosh Kumar Sah');
INSERT INTO Users (username, name) VALUES ('beanhwTbhK', 'Aayush Kumar Shah');
INSERT INTO Users (username, name) VALUES ('abdul_hafeez_khan', 'ABDUL HAFEEZ KHAN');
INSERT INTO Users (username, name) VALUES ('offcentaur', 'Abhay K Bannur');
INSERT INTO Users (username, name) VALUES ('Abhaykrgowda', 'Abhay KR');
INSERT INTO Users (username, name) VALUES ('abhaysingh42852', 'AbhayPratap Singh');
INSERT INTO Users (username, name) VALUES ('Abhilasha_jm09', 'Abhilasha J M');
INSERT INTO Users (username, name) VALUES ('Abhimaan', 'Abhimaan Konuganti');
INSERT INTO Users (username, name) VALUES ('abhinavsingh24', 'ABHINAV SINGH');
INSERT INTO Users (username, name) VALUES ('Abhineeth_Leet93', 'Abhineeth K R');
INSERT INTO Users (username, name) VALUES ('abhiram_400', 'Abhiram Aithal');
INSERT INTO Users (username, name) VALUES ('Abhi_bms', 'Abhishek');
INSERT INTO Users (username, name) VALUES ('abhishek__biradar', 'Abhishek Biradar');
INSERT INTO Users (username, name) VALUES ('Abhishek_Jirale', 'Abhishek Jirale');
INSERT INTO Users (username, name) VALUES ('abhi6feet', 'ABHISHEK K');
INSERT INTO Users (username, name) VALUES ('abhishekch938', 'Abhishek kumar choudhary');
INSERT INTO Users (username, name) VALUES ('Abhishek___S', 'Abhishek S');
INSERT INTO Users (username, name) VALUES ('achinthyam08', 'Achinthya Marpalli');
INSERT INTO Users (username, name) VALUES ('Adarsh hegde', 'Adarsh Hegde');
INSERT INTO Users (username, name) VALUES ('adarsh_mali', 'Adarsh Mali');
INSERT INTO Users (username, name) VALUES ('Adhav535', 'Adhavan K');
INSERT INTO Users (username, name) VALUES ('adhvigl', 'ADHVI GL');
INSERT INTO Users (username, name) VALUES ('adithi_md23', 'Adithi Rao');
INSERT INTO Users (username, name) VALUES ('adithi_06', 'Adithi v gouda');
INSERT INTO Users (username, name) VALUES ('Adithyamjogi25', 'Adithya M Jogi');
INSERT INTO Users (username, name) VALUES ('adithya_s_shetty57', 'Adithya S Shetty');
INSERT INTO Users (username, name) VALUES ('_AditiBalaji_', 'Aditi Balaji');
INSERT INTO Users (username, name) VALUES ('_ADITI_Chaurasiya', 'Aditi Chaurasiya');
INSERT INTO Users (username, name) VALUES ('aditishekar', 'Aditi D');
INSERT INTO Users (username, name) VALUES ('Aditi_Code123', 'Aditi Lakshmi G');
INSERT INTO Users (username, name) VALUES ('Aditi_Nagendra', 'Aditi Nagendra');
INSERT INTO Users (username, name) VALUES ('aditikulkarni96', 'Aditi Ravindra Kulkarni');
INSERT INTO Users (username, name) VALUES ('gatcoder', 'Aditya');
INSERT INTO Users (username, name) VALUES ('adiAlc', 'Aditya A');
INSERT INTO Users (username, name) VALUES ('Dadheech.aditya62@gmail.com', 'ADITYA DADHEECH');
INSERT INTO Users (username, name) VALUES ('Skull_Crew_07', 'Aditya K Bhat');
INSERT INTO Users (username, name) VALUES ('mr_jerry_', 'Aditya Kumar gupta');
INSERT INTO Users (username, name) VALUES ('Aditya__004', 'aditya kumar sahu');
INSERT INTO Users (username, name) VALUES ('Me_Adi', 'Aditya Kumar Singh');
INSERT INTO Users (username, name) VALUES ('adityakumarverma3002', 'Aditya Kumar Verma');
INSERT INTO Users (username, name) VALUES ('RSjiiyOAYf', 'Aditya Sharma');
INSERT INTO Users (username, name) VALUES ('Aditya_singhh', 'aditya singh');
INSERT INTO Users (username, name) VALUES ('ahmedibrahimp', 'Ahmed Ibrahim Padinhakara');
INSERT INTO Users (username, name) VALUES ('deshpandeakash01', 'Akash');
INSERT INTO Users (username, name) VALUES ('k_akash_2007', 'AKASH K');
INSERT INTO Users (username, name) VALUES ('Akilan_P', 'Akilan P');
INSERT INTO Users (username, name) VALUES ('Aksh_Kanwar', 'Aksh Kanwar');
INSERT INTO Users (username, name) VALUES ('akshais341', 'Akshai S');
INSERT INTO Users (username, name) VALUES ('dev_Ak05', 'Akshat Agarwal');
INSERT INTO Users (username, name) VALUES ('akshat_0709', 'Akshat Gupta');
INSERT INTO Users (username, name) VALUES ('Akshat_Codez', 'Akshat Shukla');
INSERT INTO Users (username, name) VALUES ('Akshathar', 'Akshatha R');
INSERT INTO Users (username, name) VALUES ('AkshayBasutkar', 'Akshay Basutkar');
INSERT INTO Users (username, name) VALUES ('Akshay Kulkarni', 'Akshay Kulkarni');
INSERT INTO Users (username, name) VALUES ('akshay_830', 'Akshaya Bharadhwaj C');
INSERT INTO Users (username, name) VALUES ('akshaya_ak_03', 'Akshaya M');
INSERT INTO Users (username, name) VALUES ('Akula_Sai_Likhith', 'Akula Sai Likhith');
INSERT INTO Users (username, name) VALUES ('im_ali_btw', 'Aliasgar Lakkadghat');
INSERT INTO Users (username, name) VALUES ('AlokGS777', 'Alok G S');
INSERT INTO Users (username, name) VALUES ('Alvin_st_2005', 'Alvin S Thottappilly');
INSERT INTO Users (username, name) VALUES ('AMAAN135', 'Amaan Afzal Ahmed Khan');
INSERT INTO Users (username, name) VALUES ('aman_1242004', 'AmaanTulsiyan');
INSERT INTO Users (username, name) VALUES ('Amaresh_4467', 'Amaresh S');
INSERT INTO Users (username, name) VALUES ('amirtharspriya', 'Amirtha R S');
INSERT INTO Users (username, name) VALUES ('amith__02', 'Amith gouda');
INSERT INTO Users (username, name) VALUES ('amrutha_ck128', 'Amrutha C K');
INSERT INTO Users (username, name) VALUES ('Amulya_r14', 'Amulya R');
INSERT INTO Users (username, name) VALUES ('anagha_sv', 'Anagha S Vashishta');
INSERT INTO Users (username, name) VALUES ('Anagha_NL', 'Anagha.N');
INSERT INTO Users (username, name) VALUES ('Ananya241', 'Ananya');
INSERT INTO Users (username, name) VALUES ('I_WiFight', 'Ananya Bhavesh Raut');
INSERT INTO Users (username, name) VALUES ('ananyak752004', 'Ananya Keshava');
INSERT INTO Users (username, name) VALUES ('ananyaranjith', 'Ananya Ranjith');
INSERT INTO Users (username, name) VALUES ('Ananya_S66', 'Ananya S');
INSERT INTO Users (username, name) VALUES ('Ananya_S_Belludi', 'Ananya Saikumar Belludi');
INSERT INTO Users (username, name) VALUES ('shettyana2pde', 'ananya Shetty');
INSERT INTO Users (username, name) VALUES ('Anas Shareef', 'Anas Shareef');
INSERT INTO Users (username, name) VALUES ('angelkumawat_cs1', 'Angel Kumawat');
INSERT INTO Users (username, name) VALUES ('Aniketan Shetty', 'Aniketan Shetty');
INSERT INTO Users (username, name) VALUES ('ProCoder_04', 'Aniksha Raghuveera Kamat');
INSERT INTO Users (username, name) VALUES ('AnirudhPrabhu', 'Anirudh Prabhu');
INSERT INTO Users (username, name) VALUES ('Anirudh_Rajesh', 'Anirudh Rajesh');
INSERT INTO Users (username, name) VALUES ('anjan_46', 'ANJAN B');
INSERT INTO Users (username, name) VALUES ('anjuicee', 'Anjana B Nair');
INSERT INTO Users (username, name) VALUES ('AnkitaGupta15', 'Ankita Gupta');
INSERT INTO Users (username, name) VALUES ('Qgaaheonm0', 'Ankith chowdhary');
INSERT INTO Users (username, name) VALUES ('anusm_060706', 'Annapurna Mugali');
INSERT INTO Users (username, name) VALUES ('anshmore_x0', 'Ansh More');
INSERT INTO Users (username, name) VALUES ('Anup_2006', 'Anup Bhandarkar');
INSERT INTO Users (username, name) VALUES ('ARM_24255', 'Anusha R Mahendrakar');
INSERT INTO Users (username, name) VALUES ('Anvith_Kanchan01', 'Anvith Kanchan');
INSERT INTO Users (username, name) VALUES ('AnvithaJShetty', 'Anvitha J Shetty');
INSERT INTO Users (username, name) VALUES ('Aparna_U', 'Aparna U Rao');
INSERT INTO Users (username, name) VALUES ('dnapeksha20', 'Apeksha D.N');
INSERT INTO Users (username, name) VALUES ('Aprameya019', 'Aprameya Kulkarni');
INSERT INTO Users (username, name) VALUES ('Aprameya_Venkatesh', 'Aprameya Venkatesh');
INSERT INTO Users (username, name) VALUES ('Aqsa_Mohammadi', 'Aqsa Mohammadi');
INSERT INTO Users (username, name) VALUES ('AranyaDas2007', 'Aranya Das');
INSERT INTO Users (username, name) VALUES ('Arbiyabanu', 'Arbiya banu');
INSERT INTO Users (username, name) VALUES ('archanaip', 'Archana Poojari');
INSERT INTO Users (username, name) VALUES ('Archi_Khatri', 'Archi Khatri');
INSERT INTO Users (username, name) VALUES ('arizejaz', 'Ariz Ejaz Khan');
INSERT INTO Users (username, name) VALUES ('Arpita_Gangadhar_Pattar', 'Arpita Gangadhar Pattar');
INSERT INTO Users (username, name) VALUES ('Arunank_Shankar', 'Arunank Shankar');
INSERT INTO Users (username, name) VALUES ('Aruna1506', 'Arunashree N');
INSERT INTO Users (username, name) VALUES ('Arvind322006', 'Arvind B');
INSERT INTO Users (username, name) VALUES ('Arvind_Kumaravel', 'Arvind Kumaravel');
INSERT INTO Users (username, name) VALUES ('Zero_Hand', 'Aryan Gupta');
INSERT INTO Users (username, name) VALUES ('dreameater_619', 'Aryan Rane');
INSERT INTO Users (username, name) VALUES ('AshiiiJ', 'Ashi Pathak');
INSERT INTO Users (username, name) VALUES ('_codeash_', 'Ashmith.M.A');
INSERT INTO Users (username, name) VALUES ('_AshwiniCN2004', 'Ashwini C N');
INSERT INTO Users (username, name) VALUES ('asif.cs25@bmsce.ac.in', 'Asif');
INSERT INTO Users (username, name) VALUES ('ASWIN_tech', 'ASWIN R M');
INSERT INTO Users (username, name) VALUES ('Athish_Raj2211', 'Athish Raj');
INSERT INTO Users (username, name) VALUES ('Maskd_man', 'Avik Tapadar');
INSERT INTO Users (username, name) VALUES ('amarxd', 'Avula Amarnath Reddy');
INSERT INTO Users (username, name) VALUES ('Ayush_Iyer1611', 'Ayush Iyer');
INSERT INTO Users (username, name) VALUES ('ayush_len', 'Ayush kumar');
INSERT INTO Users (username, name) VALUES ('mecyz', 'Ayushmaan Goyal');
INSERT INTO Users (username, name) VALUES ('Pavankalyanbehara37', 'B Pavan Kalyan');
INSERT INTO Users (username, name) VALUES ('BS_Amrutha', 'B S AMRUTHA VARSHINI');
INSERT INTO Users (username, name) VALUES ('vaish', 'B S Vaishnavi');
INSERT INTO Users (username, name) VALUES ('Nil', 'B V Uday Sai');
INSERT INTO Users (username, name) VALUES ('gsbhashitha', 'Bahshitha G S');
INSERT INTO Users (username, name) VALUES ('Balaganapathi_J', 'BALAGANAPATHI J');
INSERT INTO Users (username, name) VALUES ('balasubramani007', 'Balasubramani S');
INSERT INTO Users (username, name) VALUES ('batulhs', 'Batul H S');
INSERT INTO Users (username, name) VALUES ('Bharathi-Raj-V', 'Bharathi Raj V');
INSERT INTO Users (username, name) VALUES ('ABhavnaaA', 'Bhavana A');
INSERT INTO Users (username, name) VALUES ('Bhavana_revanakumar', 'Bhavana R');
INSERT INTO Users (username, name) VALUES ('bhavyat_23', 'Bhavyasri Tulasi');
INSERT INTO Users (username, name) VALUES ('Bashbhap', 'Bhoomika.B');
INSERT INTO Users (username, name) VALUES ('alphacoder01', 'Bhuvan A');
INSERT INTO Users (username, name) VALUES ('Bikashita Saha', 'Bikashita Saha');
INSERT INTO Users (username, name) VALUES ('BikkinaVenkataKedhar', 'Bikkina Venkata Kedhar');
INSERT INTO Users (username, name) VALUES ('Billgates_Raja', 'Billgates Raja N');
INSERT INTO Users (username, name) VALUES ('bisista', 'Bisista Shrestha');
INSERT INTO Users (username, name) VALUES ('biswajeetb25', 'biswajeet behera');
INSERT INTO Users (username, name) VALUES ('karthikreddyboilla', 'BOILLA KARTHIK REDDY');
INSERT INTO Users (username, name) VALUES ('brunda_s_', 'Brunda S');
INSERT INTO Users (username, name) VALUES ('Bushra_12', 'Bushra');
INSERT INTO Users (username, name) VALUES ('Chaitanyaam07', 'Chaitanya A M');
INSERT INTO Users (username, name) VALUES ('Chaithudk', 'Chaithanya.D.K');
INSERT INTO Users (username, name) VALUES ('CharanTejasV', 'Charan Tejas V');
INSERT INTO Users (username, name) VALUES ('char_s1', 'Charanyashree S');
INSERT INTO Users (username, name) VALUES ('CHAYALOKESH237', 'chaya');
INSERT INTO Users (username, name) VALUES ('Chaya03', 'Chaya M');
INSERT INTO Users (username, name) VALUES ('chetanbarakki24', 'Chetan Barakki Satish Kumar');
INSERT INTO Users (username, name) VALUES ('Chax17', 'Chethan H S');
INSERT INTO Users (username, name) VALUES ('chidambaram01', 'Chidambaram M');
INSERT INTO Users (username, name) VALUES ('chinmay_naik1', 'Chinmay M Naik');
INSERT INTO Users (username, name) VALUES ('chinmayasahu_597', 'Chinmaya Sahu');
INSERT INTO Users (username, name) VALUES ('chinmayeeg_0728', 'Chinmayee G');
INSERT INTO Users (username, name) VALUES ('CH_VIJAY2412', 'CHINNI VIJAY KUMAR');
INSERT INTO Users (username, name) VALUES ('kranthi0905', 'CHINTAKUNTA KRANTHI KUMAR REDDY');
INSERT INTO Users (username, name) VALUES ('Chinthan _G', 'Chinthan G Upadhya');
INSERT INTO Users (username, name) VALUES ('_CHIRAG_C', 'CHIRAG C');
INSERT INTO Users (username, name) VALUES ('Chiragraikar', 'CHIRAG C RAYKAR');
INSERT INTO Users (username, name) VALUES ('chiranjeevprakash', 'CHIRANJEEV O');
INSERT INTO Users (username, name) VALUES ('chiranthanasp', 'CHIRANTHANA S P');
INSERT INTO Users (username, name) VALUES ('dmdabdulrazzaq', 'D M Abdul Razzaq');
INSERT INTO Users (username, name) VALUES ('Suhas_Desu', 'D MURALI SATYA SUHAS');
INSERT INTO Users (username, name) VALUES ('manjulareddy29', 'D.Manjula');
INSERT INTO Users (username, name) VALUES ('monisha_d_15', 'D.Monisha');
INSERT INTO Users (username, name) VALUES ('darshan_dev', 'Darshan Dev');
INSERT INTO Users (username, name) VALUES ('darsh_leet', 'Darshan r palrecha');
INSERT INTO Users (username, name) VALUES ('complexboyskdv', 'Darshan S K');
INSERT INTO Users (username, name) VALUES ('Dasari_Lalit', 'Dasari lalit');
INSERT INTO Users (username, name) VALUES ('darshan-dev', 'Dashan Dev');
INSERT INTO Users (username, name) VALUES ('deepanvitha_k', 'DEEPANVITHA KATARI');
INSERT INTO Users (username, name) VALUES ('Devanand_K_Pathange05', 'DEVANAND K PATHANGE');
INSERT INTO Users (username, name) VALUES ('Devansh Shringi', 'Devansh Shringi');
INSERT INTO Users (username, name) VALUES ('deviga07', 'DEVIGA S');
INSERT INTO Users (username, name) VALUES ('Devikabinu__018', 'Devika B');
INSERT INTO Users (username, name) VALUES ('dhanushdprabhu18', 'Dhanush D Prabhu');
INSERT INTO Users (username, name) VALUES ('Dharanesh_H_M', 'Dharanesh H M');
INSERT INTO Users (username, name) VALUES ('dharshini228', 'Dharshini C');
INSERT INTO Users (username, name) VALUES ('dharyagoyal', 'Dharya Goyal');
INSERT INTO Users (username, name) VALUES ('dhruvh30', 'Dhruv H');
INSERT INTO Users (username, name) VALUES ('Dhruv677', 'Dhruv Jain');
INSERT INTO Users (username, name) VALUES ('dhruvprakash', 'Dhruv Prakash');
INSERT INTO Users (username, name) VALUES ('DHRUVK10', 'DHRUV UMESH KUNDER');
INSERT INTO Users (username, name) VALUES ('Dhyan_Sirigeri', 'Dhyan Sirigeri');
INSERT INTO Users (username, name) VALUES ('Dimlple Sathyanarayana', 'Dimple S');
INSERT INTO Users (username, name) VALUES ('Dinesh_k007', 'Dinesh K');
INSERT INTO Users (username, name) VALUES ('Dipaleenagvansh1', 'Dipalee');
INSERT INTO Users (username, name) VALUES ('dishakaranth', 'Disha Karanth');
INSERT INTO Users (username, name) VALUES ('divyavina4pi9', 'Divya Vinayaka Jothi');
INSERT INTO Users (username, name) VALUES ('DivyaS19', 'Divyashree B M');
INSERT INTO Users (username, name) VALUES ('Diya_A_J', 'Diya Anna John');
INSERT INTO Users (username, name) VALUES ('Doddabasava05', 'Doddabasava');
INSERT INTO Users (username, name) VALUES ('Caleb_John16', 'E CALEB JOHN');
INSERT INTO Users (username, name) VALUES ('vbla750', 'Eerthineni Anupama');
INSERT INTO Users (username, name) VALUES ('eshangowdadk', 'Eshan Gowda D K');
INSERT INTO Users (username, name) VALUES ('eshikaj12', 'Eshika Jaiswal');
INSERT INTO Users (username, name) VALUES ('Muffintime29', 'Etta Pranay');
INSERT INTO Users (username, name) VALUES ('Farhat_N', 'Farhat Naaz');
INSERT INTO Users (username, name) VALUES ('fazilarshiya', 'Fazil Arshiya');
INSERT INTO Users (username, name) VALUES ('GShreekar', 'G Shreekar');
INSERT INTO Users (username, name) VALUES ('Meghana Gorentla', 'G SRI SAI MEGHANA');
INSERT INTO Users (username, name) VALUES ('GVK65', 'G Vinay Karthikeyan');
INSERT INTO Users (username, name) VALUES ('DEVADHARSHINI G', 'G.Devadharshini');
INSERT INTO Users (username, name) VALUES ('gaganpkumar', 'Gagan p kumar');
INSERT INTO Users (username, name) VALUES ('gaganadm', 'Gagana D M');
INSERT INTO Users (username, name) VALUES ('GagandeepY', 'Ganagandeep Y');
INSERT INTO Users (username, name) VALUES ('Ganesh G T', 'Ganesh G T');
INSERT INTO Users (username, name) VALUES ('ganeshtp92', 'Ganeshprasad T P');
INSERT INTO Users (username, name) VALUES ('Gaurang_25', 'Gaurang');
INSERT INTO Users (username, name) VALUES ('GauravGGowda', 'Gaurav G Gowda');
INSERT INTO Users (username, name) VALUES ('ggayathrig', 'Gayathri G');
INSERT INTO Users (username, name) VALUES ('girish_0512', 'GIRISH A');
INSERT INTO Users (username, name) VALUES ('efLdXlRW1s', 'Govind');
INSERT INTO Users (username, name) VALUES ('gowthamgspatil', 'Gowtham Gs Patil');
INSERT INTO Users (username, name) VALUES ('gdedeepya_', 'Gudivada Dedeepya');
INSERT INTO Users (username, name) VALUES ('gunjansoni07', 'Gunjan Soni');
INSERT INTO Users (username, name) VALUES ('Gurupriya_Avadhani', 'Gurupriya Avadhani M M');
INSERT INTO Users (username, name) VALUES ('noob_raju', 'GV IKSHITH');
INSERT INTO Users (username, name) VALUES ('adwi_h_s', 'H S ADWI');
INSERT INTO Users (username, name) VALUES ('HAMSHITH', 'Hamshith A M');
INSERT INTO Users (username, name) VALUES ('hmhanumantha19', 'Hanumantha S');
INSERT INTO Users (username, name) VALUES ('Hariharan_Ramesh', 'HARIHARAN R');
INSERT INTO Users (username, name) VALUES ('hariharans10', 'Hariharan S');
INSERT INTO Users (username, name) VALUES ('Harini_567', 'Harini');
INSERT INTO Users (username, name) VALUES ('harini_rj_', 'Harini R J');
INSERT INTO Users (username, name) VALUES ('Harish_S_1911', 'Harish S');
INSERT INTO Users (username, name) VALUES ('Harsh_5434', 'Harsh Langote');
INSERT INTO Users (username, name) VALUES ('Harsha-MR', 'Harsha Kumar M R');
INSERT INTO Users (username, name) VALUES ('Harshavadhan_S_1343', 'Harshavardhan S');
INSERT INTO Users (username, name) VALUES ('Harshini_rnk04', 'Harshini R N K');
INSERT INTO Users (username, name) VALUES ('harshitabagrecha', 'Harshita M Jain');
INSERT INTO Users (username, name) VALUES ('_Harshitha08', 'Harshitha H.M');
INSERT INTO Users (username, name) VALUES ('harshitha797', 'Harshitha M');
INSERT INTO Users (username, name) VALUES ('Harshiii07', 'Harshitha Priyaa G R');
INSERT INTO Users (username, name) VALUES ('hemashreeg8', 'Hema Shree G');
INSERT INTO Users (username, name) VALUES ('HemantC0des', 'Hemant Singh MK');
INSERT INTO Users (username, name) VALUES ('DodgeDeflectDev', 'Hemanth R');
INSERT INTO Users (username, name) VALUES ('hemanth-07_04', 'Hemanth RS');
INSERT INTO Users (username, name) VALUES ('Hemanth_y_r', 'Hemanth Y R');
INSERT INTO Users (username, name) VALUES ('hitansh035', 'Hitansh Mittal');
INSERT INTO Users (username, name) VALUES ('amyhero_16', 'Hruthik Gowda V');
INSERT INTO Users (username, name) VALUES ('Irfan_RS', 'Irfan Sudarani');
INSERT INTO Users (username, name) VALUES ('idfjdfjids', 'Ishank');
INSERT INTO Users (username, name) VALUES ('jchandana2025', 'J Chandana');
INSERT INTO Users (username, name) VALUES ('dhanushya_05', 'J. Aron Dhanushya');
INSERT INTO Users (username, name) VALUES ('jahnavi_verma', 'Jahnavi Verma');
INSERT INTO Users (username, name) VALUES ('Kushal_2025', 'Jai Kushal C');
INSERT INTO Users (username, name) VALUES ('jainmanoujk', 'Jain Manan');
INSERT INTO Users (username, name) VALUES ('jana575', 'Janarthanan C');
INSERT INTO Users (username, name) VALUES ('jkj3553', 'Jay Kumar');
INSERT INTO Users (username, name) VALUES ('shivanvitha_jayam02', 'Jayam Shanmukha Shivanvitha');
INSERT INTO Users (username, name) VALUES ('kumarkpjayanth', 'JAYANTH KUMAR K P');
INSERT INTO Users (username, name) VALUES ('jayatej89p', 'JAYATEE CHOUDHURY');
INSERT INTO Users (username, name) VALUES ('jayshree_2511', 'Jayshree Kumari');
INSERT INTO Users (username, name) VALUES ('Jebin_Roy', 'Jebin Roy');
INSERT INTO Users (username, name) VALUES ('jedson7', 'Jedson C');
INSERT INTO Users (username, name) VALUES ('JeevaFermat', 'Jeeva J');
INSERT INTO Users (username, name) VALUES ('jeevankunter19', 'Jeevan Ravindra Kunter');
INSERT INTO Users (username, name) VALUES ('jeevan__53', 'Jeevan S');
INSERT INTO Users (username, name) VALUES ('jenushs', 'Jenush S');
INSERT INTO Users (username, name) VALUES ('joyeunice15', 'Joy Eunice S');
INSERT INTO Users (username, name) VALUES ('nihums', 'K P Hamssini');
INSERT INTO Users (username, name) VALUES ('shashank_hathwar', 'K.G.Shashank Hathwar');
INSERT INTO Users (username, name) VALUES ('kalpitha06', 'KALPITHA BV');
INSERT INTO Users (username, name) VALUES ('kalyani__21', 'Kalyani Kolpe');
INSERT INTO Users (username, name) VALUES ('itadoriii', 'Kanakagiri Phani Samvith');
INSERT INTO Users (username, name) VALUES ('kanavpatel', 'Kanav patel');
INSERT INTO Users (username, name) VALUES ('jahnavi1125k', 'KANDULA JAHNAVI');
INSERT INTO Users (username, name) VALUES ('KANISHKARR24', 'KANISHKA R R');
INSERT INTO Users (username, name) VALUES ('Saicharan_2005', 'Kappa Sai Charan Raju');
INSERT INTO Users (username, name) VALUES ('Karthiga', 'Karthiga N');
INSERT INTO Users (username, name) VALUES ('Karthik__T', 'Karthik T');
INSERT INTO Users (username, name) VALUES ('Karthika_Velan_S', 'Karthika Velan S');
INSERT INTO Users (username, name) VALUES ('karthiyayini1911', 'KARTHIYAYINI R');
INSERT INTO Users (username, name) VALUES ('Kartikkulal', 'Kartik kulal');
INSERT INTO Users (username, name) VALUES ('Jhon_wick_1969', 'Kartik S Ghorpade');
INSERT INTO Users (username, name) VALUES ('S_KASTHURI', 'KASTHURI S');
INSERT INTO Users (username, name) VALUES ('kathyayini2407', 'Kathyayini Prabhu');
INSERT INTO Users (username, name) VALUES ('KavanaKJ', 'Kavana K J');
INSERT INTO Users (username, name) VALUES ('kavyadeepdev', 'Kavyadeep Dev');
INSERT INTO Users (username, name) VALUES ('KedarD37', 'Kedar Desai');
INSERT INTO Users (username, name) VALUES ('Kpk', 'Keerat Prabh Kaur');
INSERT INTO Users (username, name) VALUES ('Keerthana21_', 'Keerthana B');
INSERT INTO Users (username, name) VALUES ('Keerthanat1', 'Keerthana T');
INSERT INTO Users (username, name) VALUES ('Keerti', 'Keerti dodamani');
INSERT INTO Users (username, name) VALUES ('Kevan_123', 'Kevan Patira');
INSERT INTO Users (username, name) VALUES ('GoCi7WEREW', 'Khushi B Chilakawad');
INSERT INTO Users (username, name) VALUES ('Kiranmk1803', 'Kiran M K');
INSERT INTO Users (username, name) VALUES ('Kirthikha_J', 'Kirthikha.J');
INSERT INTO Users (username, name) VALUES ('Kirti_Singhh10', 'Kirti Singh');
INSERT INTO Users (username, name) VALUES ('kirubakarans2204', 'KIRUBAKARAN S');
INSERT INTO Users (username, name) VALUES ('kishan__b', 'Kishan b');
INSERT INTO Users (username, name) VALUES ('KishooreVC', 'Kishoore V C');
INSERT INTO Users (username, name) VALUES ('saketh3425', 'Kollu Saketharam');
INSERT INTO Users (username, name) VALUES ('C0BoZxYPKC', 'Konakalla Meenakshi');
INSERT INTO Users (username, name) VALUES ('Kopparam_Yathin', 'Kopparam Yathin');
INSERT INTO Users (username, name) VALUES ('4FWdfFuWVt', 'Kopparapu Bhargava Narasimha');
INSERT INTO Users (username, name) VALUES ('KOPPARAPUNAVATEJA', 'Kopparapu navateja');
INSERT INTO Users (username, name) VALUES ('kovurumahendra_1', 'KOVURU MAHENDRA');
INSERT INTO Users (username, name) VALUES ('kritarth_teli', 'Kritarth Teli');
INSERT INTO Users (username, name) VALUES ('guduru_kruthi', 'Kruthi Guduru');
INSERT INTO Users (username, name) VALUES ('Kshama_Bhat', 'Kshama Bhat');
INSERT INTO Users (username, name) VALUES ('kshitijk89', 'Kshitij K');
INSERT INTO Users (username, name) VALUES ('adiiiiitya', 'Kumar Aditya Singh');
INSERT INTO Users (username, name) VALUES ('Kushagra757', 'Kushagra Siddha');
INSERT INTO Users (username, name) VALUES ('Kushalbn7676', 'Kushal B N');
INSERT INTO Users (username, name) VALUES ('kushalkumar_119', 'KUSHAL KUMAR N');
INSERT INTO Users (username, name) VALUES ('kushall33', 'Kushal Murarka');
INSERT INTO Users (username, name) VALUES ('bklahari7', 'LAHARI B K');
INSERT INTO Users (username, name) VALUES ('Lakshmikanthbr Br', 'Lakshmi Kanth B R');
INSERT INTO Users (username, name) VALUES ('LakshmikantGH', 'Lakshmikant hunachal');
INSERT INTO Users (username, name) VALUES ('lalit_7732', 'Lalit kumar Sureliya');
INSERT INTO Users (username, name) VALUES ('lathi31', 'LATHIKA C');
INSERT INTO Users (username, name) VALUES ('Lathika_25', 'Lathika M');
INSERT INTO Users (username, name) VALUES ('Laxmia_', 'Laxmi M A');
INSERT INTO Users (username, name) VALUES ('GHp2oz8UYj', 'Lekhana M');
INSERT INTO Users (username, name) VALUES ('Likhith_RajaKumar', 'Likhith R');
INSERT INTO Users (username, name) VALUES ('Likith_R', 'LIKITH R');
INSERT INTO Users (username, name) VALUES ('LikithaShree', 'Likitha Shree S R');
INSERT INTO Users (username, name) VALUES ('lochanchennur', 'LOCHAN G CHENNUR');
INSERT INTO Users (username, name) VALUES ('lochangowda01', 'Lochan Gowda T M');
INSERT INTO Users (username, name) VALUES ('loge_sh18', 'Logesh K');
INSERT INTO Users (username, name) VALUES ('lohithcoder07', 'Lohith M');
INSERT INTO Users (username, name) VALUES ('LOPAMUDRA_PATRO', 'Lopamudra Patro');
INSERT INTO Users (username, name) VALUES ('Abhinav M', 'M Abhinav');
INSERT INTO Users (username, name) VALUES ('Afnaan_ali26', 'M Afnaan Ali');
INSERT INTO Users (username, name) VALUES ('Amarnath_Medar', 'M Amarnath');
INSERT INTO Users (username, name) VALUES ('_bhushan_1', 'M Bhushan');
INSERT INTO Users (username, name) VALUES ('mdzameer', 'M D Zameer Hussain');
INSERT INTO Users (username, name) VALUES ('naimi_2006', 'M Naimi Sai Ganesh');
INSERT INTO Users (username, name) VALUES ('Jijnash2636', 'M. Jijnash kumar');
INSERT INTO Users (username, name) VALUES ('Ruba_Sri_05', 'M.Ruba Sri');
INSERT INTO Users (username, name) VALUES ('MALYAVANTHAMSAIPRANEETHA', 'M.Sai Praneetha');
INSERT INTO Users (username, name) VALUES ('Santhosh2027', 'M.Santhosh');
INSERT INTO Users (username, name) VALUES ('medehal_shravya', 'M.Shravya');
INSERT INTO Users (username, name) VALUES ('sathvik1404', 'Madhireddy Sathvik Reddy');
INSERT INTO Users (username, name) VALUES ('madhulika13', 'Madhulika Praveen');
INSERT INTO Users (username, name) VALUES ('Madhumita_Venkatesh', 'Madhumita Venkatesh');
INSERT INTO Users (username, name) VALUES ('Madhumithark', 'MADHUMITHA R K');
INSERT INTO Users (username, name) VALUES ('bhanukiran29', 'Madisetty Bhanu Kiran');
INSERT INTO Users (username, name) VALUES ('mahalakshmir338', 'Mahalakshmi');
INSERT INTO Users (username, name) VALUES ('MahathiSrinath', 'Mahathi Srinath');
INSERT INTO Users (username, name) VALUES ('mahihesh13', 'Mahesh Bhupendra Kumar Borana');
INSERT INTO Users (username, name) VALUES ('mahesh1008', 'Mahesh Rajpurohit');
INSERT INTO Users (username, name) VALUES ('Mahima_Koul', 'Mahima Koul');
INSERT INTO Users (username, name) VALUES ('snk_17', 'Malyala Sonika');
INSERT INTO Users (username, name) VALUES ('Manasa54', 'Manasa GR');
INSERT INTO Users (username, name) VALUES ('Manasahs_24', 'Manasa HS');
INSERT INTO Users (username, name) VALUES ('Manasa02_', 'Manasa T');
INSERT INTO Users (username, name) VALUES ('maannasviiii29', 'Manasvi Singh');
INSERT INTO Users (username, name) VALUES ('ManaswiAsutkar', 'Manaswi Asutkar');
INSERT INTO Users (username, name) VALUES ('Mandeep_singh_82', 'Mandeep Singh');
INSERT INTO Users (username, name) VALUES ('MANOJ_G_R', 'MANOJ G R');
INSERT INTO Users (username, name) VALUES ('manoj182007', 'Manoj kumar');
INSERT INTO Users (username, name) VALUES ('Manojnaik122', 'Manoj Madev Naik');
INSERT INTO Users (username, name) VALUES ('OlrUfVf9x3', 'Mansi A');
INSERT INTO Users (username, name) VALUES ('Marish_Seenivasagan', 'marish s');
INSERT INTO Users (username, name) VALUES ('Mayeraa', 'Mayeraa Singh');
INSERT INTO Users (username, name) VALUES ('md_ashraf4537', 'Md Ashraf');
INSERT INTO Users (username, name) VALUES ('hkmedha38', 'Medha H K');
INSERT INTO Users (username, name) VALUES ('Medhansh_works', 'Medhansh Agrawal');
INSERT INTO Users (username, name) VALUES ('megha_hiremath', 'Megha');
INSERT INTO Users (username, name) VALUES ('Merinmaria@123', 'Merin Maria Vincent');
INSERT INTO Users (username, name) VALUES ('MERLIN SAVITHA', 'Merlin Thanga Savitha R');
INSERT INTO Users (username, name) VALUES ('mirzafayaz', 'Mirza fayaz');
INSERT INTO Users (username, name) VALUES ('sponge', 'Mohamed Nabeel Fayaz N');
INSERT INTO Users (username, name) VALUES ('_yakub_bhai', 'Mohammad Yakub');
INSERT INTO Users (username, name) VALUES ('arshaq777', 'Mohammed Arshaq T');
INSERT INTO Users (username, name) VALUES ('mohdfahim', 'Mohammed Fahim');
INSERT INTO Users (username, name) VALUES ('Md_Khalander_CSE123', 'Mohammed Khalander');
INSERT INTO Users (username, name) VALUES ('Nabeel_25', 'Mohammed Nabeel');
INSERT INTO Users (username, name) VALUES ('Mohammed-Raiyaan', 'MOHAMMED RAIYAAN');
INSERT INTO Users (username, name) VALUES ('mohanvitta_7', 'Mohan Krishna');
INSERT INTO Users (username, name) VALUES ('Mighty__Mohit', 'Mohit Kumar');
INSERT INTO Users (username, name) VALUES ('Mohnish_Sahu_1', 'MOHNISH SAHU');
INSERT INTO Users (username, name) VALUES ('monish__07', 'Monish D');
INSERT INTO Users (username, name) VALUES ('CalmOutlaws7', 'Monish M');
INSERT INTO Users (username, name) VALUES ('Monisha 26M', 'MONISHA M');
INSERT INTO Users (username, name) VALUES ('monisharavindra', 'Monisha R');
INSERT INTO Users (username, name) VALUES ('Monisha_S12', 'MONISHA S');
INSERT INTO Users (username, name) VALUES ('mouneshwar_cs24', 'Mouneshwar');
INSERT INTO Users (username, name) VALUES ('Mukeshbabu_', 'Mukesh babu A');
INSERT INTO Users (username, name) VALUES ('Tejeswara_raju9', 'Muppala Tejeswara raju');
INSERT INTO Users (username, name) VALUES ('Murali_831', 'Murali A');
INSERT INTO Users (username, name) VALUES ('gupta_muskan16', 'Muskan Gupta');
INSERT INTO Users (username, name) VALUES ('Mythreyee MT (923_123)-ID', 'Mythreyee MT');
INSERT INTO Users (username, name) VALUES ('N__HARSHITHA', 'N HARSHITHA');
INSERT INTO Users (username, name) VALUES ('ZachTheNabi', 'Nabi Abhishikth Zacharias');
INSERT INTO Users (username, name) VALUES ('nagalakshmi_s08', 'Nagalakshmi s');
INSERT INTO Users (username, name) VALUES ('Naincy33', 'Naincy');
INSERT INTO Users (username, name) VALUES ('Nalla_Tejaswini', 'Nalla Tejaswini');
INSERT INTO Users (username, name) VALUES ('sindz_22', 'Nalluri Sindhuja');
INSERT INTO Users (username, name) VALUES ('Naman_kr_ag', 'Naman Kumar Agrawal');
INSERT INTO Users (username, name) VALUES ('nameeta0260', 'Nameeta M');
INSERT INTO Users (username, name) VALUES ('NLingjelleima', 'Nameirakpam Lingjelleima');
INSERT INTO Users (username, name) VALUES ('namrata_1606', 'Namrata Adiga');
INSERT INTO Users (username, name) VALUES ('nandanakishorecnair', 'Nandana Kishore C Nair');
INSERT INTO Users (username, name) VALUES ('saisreekar6040', 'Nandepu sai sreekar');
INSERT INTO Users (username, name) VALUES ('nandhana25', 'Nandhana Y');
INSERT INTO Users (username, name) VALUES ('nandhi12', 'Nandhini J');
INSERT INTO Users (username, name) VALUES ('Nandini_K_B', 'Nandini K B');
INSERT INTO Users (username, name) VALUES ('Nanditha_karkera', 'Nanditha');
INSERT INTO Users (username, name) VALUES ('Nanditha1209', 'Nanditha.R');
INSERT INTO Users (username, name) VALUES ('Naresh_006', 'Naresh S');
INSERT INTO Users (username, name) VALUES ('natalipawar1', 'Natali Pawar');
INSERT INTO Users (username, name) VALUES ('Navaneet_S', 'Navaneet.S');
INSERT INTO Users (username, name) VALUES ('NavaneethaKrishan', 'Navaneetha Krishan S');
INSERT INTO Users (username, name) VALUES ('Navaneethakrishnan.P', 'Navaneethakrishnan.P');
INSERT INTO Users (username, name) VALUES ('Navin665', 'Naveen kumar N');
INSERT INTO Users (username, name) VALUES ('naveenmk01', 'Naveen m k');
INSERT INTO Users (username, name) VALUES ('Navneet017', 'Navneet');
INSERT INTO Users (username, name) VALUES ('navyabv', 'Navya B V');
INSERT INTO Users (username, name) VALUES ('nayansarda07', 'Nayan Sarda');
INSERT INTO Users (username, name) VALUES ('Nayana_N', 'Nayana N');
INSERT INTO Users (username, name) VALUES ('neelx8', 'Neel Prashanth');
INSERT INTO Users (username, name) VALUES ('neerajnp', 'Neeraj N Pathange');
INSERT INTO Users (username, name) VALUES ('Veen', 'Neev jaiswal');
INSERT INTO Users (username, name) VALUES ('negbcfs', 'NEGA M');
INSERT INTO Users (username, name) VALUES ('Curious_coder123', 'Neha Bhaskar');
INSERT INTO Users (username, name) VALUES ('sahnehaa', 'Neha kumari sah');
INSERT INTO Users (username, name) VALUES ('nuhuh', 'Neha Ramiah');
INSERT INTO Users (username, name) VALUES ('neha_07321', 'Neha Singh');
INSERT INTO Users (username, name) VALUES ('nehaa_06', 'Nehaa S Prasad');
INSERT INTO Users (username, name) VALUES ('Nidhi Kumari', 'Nidhi Kumari');
INSERT INTO Users (username, name) VALUES ('nidhisahare', 'Nidhi Sahare');
INSERT INTO Users (username, name) VALUES ('Niketh_P', 'Niketh P');
INSERT INTO Users (username, name) VALUES ('Nikhil-_', 'Nikhil');
INSERT INTO Users (username, name) VALUES ('_Nikhil_C_', 'Nikhil C');
INSERT INTO Users (username, name) VALUES ('Nikhitha_Prabhu', 'Nikhitha JP');
INSERT INTO Users (username, name) VALUES ('nikhithas11', 'Nikhitha.S');
INSERT INTO Users (username, name) VALUES ('Nikil_J', 'Nikil J');
INSERT INTO Users (username, name) VALUES ('Nirajsinghns_82222', 'Niraj Kumar Singh');
INSERT INTO Users (username, name) VALUES ('niranjan_2306', 'Niranjan K');
INSERT INTO Users (username, name) VALUES ('Niranjangouda Patil', 'Niranjangouda Patil');
INSERT INTO Users (username, name) VALUES ('Nisha957', 'Nisha');
INSERT INTO Users (username, name) VALUES ('nishalnayak', 'Nishal Radhakrishna Nayak');
INSERT INTO Users (username, name) VALUES ('nishanthm621', 'Nishanth M');
INSERT INTO Users (username, name) VALUES ('nithin477', 'Nithin E T');
INSERT INTO Users (username, name) VALUES ('Nithish_Nk2006', 'Nithish Kumar S');
INSERT INTO Users (username, name) VALUES ('Nithyashree_Nataraj', 'Nithyashree Nataraj');
INSERT INTO Users (username, name) VALUES ('nitya_pawar', 'Nitya R Pawar');
INSERT INTO Users (username, name) VALUES ('Niveditha_HGN', 'Niveditha H G');
INSERT INTO Users (username, name) VALUES ('npnerajnp', 'NP NERAJ REDDY');
INSERT INTO Users (username, name) VALUES ('kaduom444', 'Om Nilesh Kadu');
INSERT INTO Users (username, name) VALUES ('omkar_005', 'Omkar Dhumal');
INSERT INTO Users (username, name) VALUES ('1WN24CS189', 'P DURGANANDAN V BHAT');
INSERT INTO Users (username, name) VALUES ('su2OPy5CWl', 'P R Shreevatsa');
INSERT INTO Users (username, name) VALUES ('psowmyasreey1si', 'P Sowmya Sree');
INSERT INTO Users (username, name) VALUES ('PRM_095', 'P.Rama Manogna');
INSERT INTO Users (username, name) VALUES ('Padmini_Swaranam_S (Email - swaranasaran535@gmail.com)', 'PADMINI SWARANAM S');
INSERT INTO Users (username, name) VALUES ('Palaniappan_05', 'Palaniappan S');
INSERT INTO Users (username, name) VALUES ('hitz_codes', 'paleti hithaishi hrushikesh');
INSERT INTO Users (username, name) VALUES ('Pallaviv_990', 'PALLAVI V');
INSERT INTO Users (username, name) VALUES ('panchami_p', 'Panchami P');
INSERT INTO Users (username, name) VALUES ('paras_ydv', 'Paras');
INSERT INTO Users (username, name) VALUES ('parikshithdk06', 'Parikshith D Kanchan');
INSERT INTO Users (username, name) VALUES ('parthkolekar_29', 'Parth Kolekar');
INSERT INTO Users (username, name) VALUES ('parvjain_24', 'Parv Jain');
INSERT INTO Users (username, name) VALUES ('pavanrn_124', 'PAVAN R N');
INSERT INTO Users (username, name) VALUES ('pavankumar2501', 'Pavankumar Mudagal');
INSERT INTO Users (username, name) VALUES ('pavi_10', 'PAVITHA P');
INSERT INTO Users (username, name) VALUES ('pavithravyas', 'Pavithravyas k');
INSERT INTO Users (username, name) VALUES ('pooja_0713', 'Pooja K');
INSERT INTO Users (username, name) VALUES ('Pooja_sridharan', 'Pooja P K S');
INSERT INTO Users (username, name) VALUES ('pooja shah', 'Pooja shah');
INSERT INTO Users (username, name) VALUES ('Poo-12345', 'Poojashree s');
INSERT INTO Users (username, name) VALUES ('Poojitha8', 'poojithab');
INSERT INTO Users (username, name) VALUES ('Poornesh_K', 'POORNESH K');
INSERT INTO Users (username, name) VALUES ('Poorvi B', 'poorvi bisali');
INSERT INTO Users (username, name) VALUES ('learnwith22', 'POORVI V SHETTY');
INSERT INTO Users (username, name) VALUES ('Poorvikanaik', 'Poorvika C Naik');
INSERT INTO Users (username, name) VALUES ('Poorvika_H', 'Poorvika H');
INSERT INTO Users (username, name) VALUES ('pradeepss25', 'Pradeep S S');
INSERT INTO Users (username, name) VALUES ('spradeepa@student.tce.edu', 'PRADEEPA S');
INSERT INTO Users (username, name) VALUES ('Pra_24', 'Pradnya Bhosale');
INSERT INTO Users (username, name) VALUES ('pragati1509', 'Pragati B Suresh');
INSERT INTO Users (username, name) VALUES ('Prajwal7725', 'Prajwal Y');
INSERT INTO Users (username, name) VALUES ('pramish_bsl', 'Pramish Bhusal');
INSERT INTO Users (username, name) VALUES ('PranamyaPrakash', 'Pranamya Prakash Rayakar');
INSERT INTO Users (username, name) VALUES ('Pranatha_M_R', 'Pranatha M R');
INSERT INTO Users (username, name) VALUES ('Pranati_ap', 'Pranati A P');
INSERT INTO Users (username, name) VALUES ('2006pranav', 'Pranav');
INSERT INTO Users (username, name) VALUES ('Pranav_PM245', 'Pranav PM');
INSERT INTO Users (username, name) VALUES ('Praneesha_Arvapalli', 'Praneesha Arvapalli');
INSERT INTO Users (username, name) VALUES ('Praneeth_Nandan_R', 'Praneeth Nandan. R');
INSERT INTO Users (username, name) VALUES ('Praneetha_adiga_30', 'Praneetha');
INSERT INTO Users (username, name) VALUES ('PRANITHKUMARCA123', 'PRANITH KUMAR CA');
INSERT INTO Users (username, name) VALUES ('pprarthanak', 'Prarthana K');
INSERT INTO Users (username, name) VALUES ('_PRARTHANA_M', 'Prarthana M');
INSERT INTO Users (username, name) VALUES ('prarthanamahesh2', 'Prarthana Mahesh');
INSERT INTO Users (username, name) VALUES ('prarthana_patil', 'Prarthana patil');
INSERT INTO Users (username, name) VALUES ('404pjfound', 'Prasanna Jain');
INSERT INTO Users (username, name) VALUES ('pkg15006', 'Pratham Gavadia');
INSERT INTO Users (username, name) VALUES ('Pratham K P', 'Pratham K P');
INSERT INTO Users (username, name) VALUES ('prabhuppratham', 'Pratham Praveen Prabhu');
INSERT INTO Users (username, name) VALUES ('pratheekselvan-jpg', 'Pratheek TS');
INSERT INTO Users (username, name) VALUES ('pratheeksha_sd', 'PRATHEEKSHA S DODAMANI');
INSERT INTO Users (username, name) VALUES ('pratheeth143', 'Pratheeth S Angari');
INSERT INTO Users (username, name) VALUES ('1WN24CS203', 'Prathyush Jain M');
INSERT INTO Users (username, name) VALUES ('Pratibha Prakash', 'Pratibha Prakash Khavasad');
INSERT INTO Users (username, name) VALUES ('pratikjana0309', 'Pratik Jana');
INSERT INTO Users (username, name) VALUES ('Preetam-R', 'Preetam Rathod');
INSERT INTO Users (username, name) VALUES ('Preethi_S_', 'Preethi S');
INSERT INTO Users (username, name) VALUES ('preethi_969', 'Preethi Vinnakota');
INSERT INTO Users (username, name) VALUES ('Preethi.S', 'Preethi.S');
INSERT INTO Users (username, name) VALUES ('Prem Manghani', 'Prem Manghani');
INSERT INTO Users (username, name) VALUES ('Prem_Rathod', 'Prem Rathod');
INSERT INTO Users (username, name) VALUES ('Pri_Shetty', 'Priya S');
INSERT INTO Users (username, name) VALUES ('Priyanshu_acharya07', 'Priyanshu Acharya');
INSERT INTO Users (username, name) VALUES ('Purv567', 'Purvi. S');
INSERT INTO Users (username, name) VALUES ('PC2006', 'Pushkar C');
INSERT INTO Users (username, name) VALUES ('Pushpa cs02', 'Pushpa S D');
INSERT INTO Users (username, name) VALUES ('balajepriyan', 'R Balaje Priyan');
INSERT INTO Users (username, name) VALUES ('Sid129076', 'R S Siddharth');
INSERT INTO Users (username, name) VALUES ('rvabhi2504', 'R V Abhishek');
INSERT INTO Users (username, name) VALUES ('madhumitha_1607', 'R.Madhumitha');
INSERT INTO Users (username, name) VALUES ('Rachana_Devadiga', 'Rachana');
INSERT INTO Users (username, name) VALUES ('Rachanas_18', 'Rachana S');
INSERT INTO Users (username, name) VALUES ('Rachanaa_p', 'Radhika P K');
INSERT INTO Users (username, name) VALUES ('Ragasudha2409', 'RAGASUDHA B');
INSERT INTO Users (username, name) VALUES ('_Raghavendra', 'Raghavendra R');
INSERT INTO Users (username, name) VALUES ('dsraghavv7tu', 'Raghavendra.D.S');
INSERT INTO Users (username, name) VALUES ('rsah90001-source', 'Rahul Kumar Sah');
INSERT INTO Users (username, name) VALUES ('just__Rahul', 'Rahul Pal');
INSERT INTO Users (username, name) VALUES ('RahulS21', 'Rahul S Srivastava');
INSERT INTO Users (username, name) VALUES ('broke08rp', 'Rajan Patel');
INSERT INTO Users (username, name) VALUES ('rajarshi_1010', 'Rajarshi Ghosh');
INSERT INTO Users (username, name) VALUES ('RajivPrasadKushwaha', 'Rajiv Prasad Kushwaha');
INSERT INTO Users (username, name) VALUES ('rakeshKumarm081', 'Rakesh Kumar');
INSERT INTO Users (username, name) VALUES ('Venkat Koushik Ramisetty', 'Ramisetty Venkat Koushik');
INSERT INTO Users (username, name) VALUES ('Ranjani_22', 'Ranjani S');
INSERT INTO Users (username, name) VALUES ('rashmithanaik23', 'Rashmitha Naik');
INSERT INTO Users (username, name) VALUES ('ratikagrawal30', 'Ratik Agrawal');
INSERT INTO Users (username, name) VALUES ('Ravi_Teja_S', 'Ravi Teja S');
INSERT INTO Users (username, name) VALUES ('Rayyan004', 'Rayyan Zaniullabidin');
INSERT INTO Users (username, name) VALUES ('razaid2006', 'Razaid Aziz K');
INSERT INTO Users (username, name) VALUES ('RenganayakiMurugesh', 'Renganayaki Murugesh');
INSERT INTO Users (username, name) VALUES ('resham-nk42', 'RESHAM SANTOSH NAIK');
INSERT INTO Users (username, name) VALUES ('Ridhima_04', 'Ridhima Chhabra');
INSERT INTO Users (username, name) VALUES ('r1shabhgarg', 'Rishabh Garg');
INSERT INTO Users (username, name) VALUES ('jaiswalrishabh07', 'Rishabh Jaiswal');
INSERT INTO Users (username, name) VALUES ('RISHI KUMAR R', 'RISHI KUMAR R');
INSERT INTO Users (username, name) VALUES ('rishika_gowda0501', 'RISHIKA GOWDA M');
INSERT INTO Users (username, name) VALUES ('rishikamanot_02', 'Rishika Manot');
INSERT INTO Users (username, name) VALUES ('Rishith_A', 'Rishith Ananthan');
INSERT INTO Users (username, name) VALUES ('rishithsrinivas1', 'Rishith.S');
INSERT INTO Users (username, name) VALUES ('rishvedha', 'Rishvedha M');
INSERT INTO Users (username, name) VALUES ('Vilgax_1010', 'Ritesh Mohan Nayak');
INSERT INTO Users (username, name) VALUES ('Rithanyakr26', 'Rithanya K R');
INSERT INTO Users (username, name) VALUES ('ritika_addepalli', 'Ritika A');
INSERT INTO Users (username, name) VALUES ('RitikhaRJ', 'Ritikha Raj');
INSERT INTO Users (username, name) VALUES ('itz_riya073', 'Riya kumari');
INSERT INTO Users (username, name) VALUES ('codedbyrohan', 'Rohan Gangal');
INSERT INTO Users (username, name) VALUES ('rohanr_cd23', 'Rohan R');
INSERT INTO Users (username, name) VALUES ('723bIDnMwI', 'Rohan R');
INSERT INTO Users (username, name) VALUES ('RohiniR008', 'Rohini R');
INSERT INTO Users (username, name) VALUES ('ROHITHB7', 'Rohith B');
INSERT INTO Users (username, name) VALUES ('Rohith_kumar08', 'Rohith Kumar');
INSERT INTO Users (username, name) VALUES ('Roja-H-S', 'Roja H S');
INSERT INTO Users (username, name) VALUES ('roshaniudupats', 'Roshani T S Udupa');
INSERT INTO Users (username, name) VALUES ('Ruchitha C S', 'RUCHITHA C S');
INSERT INTO Users (username, name) VALUES ('RuqaiyyaM', 'Ruqaiyya Mahreen');
INSERT INTO Users (username, name) VALUES ('rishibhsie33', 'Rushikesh Rajaram bhise');
INSERT INTO Users (username, name) VALUES ('iamsasushanth07', 'S A Sushanth');
INSERT INTO Users (username, name) VALUES ('phoenix20040205', 'S Arvindhan');
INSERT INTO Users (username, name) VALUES ('S_Nagashree', 'S Nagashree');
INSERT INTO Users (username, name) VALUES ('thanisha_07', 'S S Thanisha Shree');
INSERT INTO Users (username, name) VALUES ('udaysai_kumar', 'S Uday Sai Kumar');
INSERT INTO Users (username, name) VALUES ('uditareddy', 'S Udita reddy');
INSERT INTO Users (username, name) VALUES ('Sahana_270', 'SAHANA BK');
INSERT INTO Users (username, name) VALUES ('Sahil21db', 'Sahil Jain');
INSERT INTO Users (username, name) VALUES ('SK064738', 'SAHIL KUMAR');
INSERT INTO Users (username, name) VALUES ('Voidx_369', 'Sahil nivrutti pachpor');
INSERT INTO Users (username, name) VALUES ('sahithya_arjunan', 'Sahithya Arjunan');
INSERT INTO Users (username, name) VALUES ('TheFlyingPekka', 'Sai Chiranth.M');
INSERT INTO Users (username, name) VALUES ('Saikrishna_1006', 'Sai Krishna Girish Hallikeri');
INSERT INTO Users (username, name) VALUES ('NANDINI_62', 'Sai Nandhini');
INSERT INTO Users (username, name) VALUES ('sharadha15490', 'Sai Sharadha Manjunath');
INSERT INTO Users (username, name) VALUES ('Saiteja2907', 'Sai Teja k');
INSERT INTO Users (username, name) VALUES ('MoFra', 'Sai Ujwal P');
INSERT INTO Users (username, name) VALUES ('saikiran_shet9800', 'Saikiran K Shet');
INSERT INTO Users (username, name) VALUES ('Sainath_3902u', 'Sainath');
INSERT INTO Users (username, name) VALUES ('5aketh', 'Saketh Ram Arepalli');
INSERT INTO Users (username, name) VALUES ('sakthisanjana', 'Sakthi Sanjana S');
INSERT INTO Users (username, name) VALUES ('sakthiprroq2', 'SAKTHIPRIYA L');
INSERT INTO Users (username, name) VALUES ('ssakthi2007', 'Sakthivel S');
INSERT INTO Users (username, name) VALUES ('salman', 'salman sk');
INSERT INTO Users (username, name) VALUES ('samanth_1105', 'Samanth Melmane');
INSERT INTO Users (username, name) VALUES ('1R8Xekj1Hq', 'Samanyu Gupta');
INSERT INTO Users (username, name) VALUES ('samarthj1928', 'Samarth Joshi');
INSERT INTO Users (username, name) VALUES ('Samarth0710', 'Samarth Prasad');
INSERT INTO Users (username, name) VALUES ('samaya5432', 'Samaya Harshitha.N');
INSERT INTO Users (username, name) VALUES ('Sammita_12', 'Sammita Abhay');
INSERT INTO Users (username, name) VALUES ('sampritahatti07', 'Samprita s Hatti');
INSERT INTO Users (username, name) VALUES ('SAMRUDH_A_V', 'Samrudh A V');
INSERT INTO Users (username, name) VALUES ('sksamya21', 'Samya Kumari');
INSERT INTO Users (username, name) VALUES ('sanam_2008', 'Sanam dharamveer bhadoriya');
INSERT INTO Users (username, name) VALUES ('sandhiyapushpakumar', 'Sandhiya p');
INSERT INTO Users (username, name) VALUES ('sandra-04092006', 'Sandra S');
INSERT INTO Users (username, name) VALUES ('siddhusss07', 'Sangeeth Siddharth S');
INSERT INTO Users (username, name) VALUES ('Sangee_2004', 'SANGEETHA BK');
INSERT INTO Users (username, name) VALUES ('Sanghamithraa7', 'SANGHAMITHRAA E');
INSERT INTO Users (username, name) VALUES ('sanidhyab', 'Sanidhya B');
INSERT INTO Users (username, name) VALUES ('Sanil', 'Sanil');
INSERT INTO Users (username, name) VALUES ('Saniya', 'Saniya');
INSERT INTO Users (username, name) VALUES ('sanjanak_ai23', 'Sanjana K');
INSERT INTO Users (username, name) VALUES ('sanjana_298', 'Sanjana k T');
INSERT INTO Users (username, name) VALUES ('uzXg7HflnV', 'Sanjana M');
INSERT INTO Users (username, name) VALUES ('sanjaygowdahd', 'Sanjay gowda hd');
INSERT INTO Users (username, name) VALUES ('JyFYW8Mx0e', 'Sanjay Ruban S');
INSERT INTO Users (username, name) VALUES ('sanmitha16_', 'Sanmitha Mujumdar');
INSERT INTO Users (username, name) VALUES ('momo1734', 'sanskar raut');
INSERT INTO Users (username, name) VALUES ('santoshkumarad1', 'Santosh Kumar Gupta Rouniyar');
INSERT INTO Users (username, name) VALUES ('Sanyagomathi', 'Sanya Gomathi');
INSERT INTO Users (username, name) VALUES ('sapnaa_ee23', 'Sapna A Jain');
INSERT INTO Users (username, name) VALUES ('Photonic_Mouse', 'Saquib S Nadaf');
INSERT INTO Users (username, name) VALUES ('sara_khurshida', 'Sara Khurshida');
INSERT INTO Users (username, name) VALUES ('sarangpathari4', 'Sarang P');
INSERT INTO Users (username, name) VALUES ('Saranya', 'Saranya S');
INSERT INTO Users (username, name) VALUES ('sareddypoojyasr1', 'Sareddy Poojya Sree');
INSERT INTO Users (username, name) VALUES ('Sath_vika', 'Sathvika PP');
INSERT INTO Users (username, name) VALUES ('Satish6974', 'Satish Kumar H');
INSERT INTO Users (username, name) VALUES ('Satyam_kumar_jha_21', 'Satyam kumar jha');
INSERT INTO Users (username, name) VALUES ('satyamsinha442', 'Satyam Sinha');
INSERT INTO Users (username, name) VALUES ('saugataei23', 'Saugata Debnath');
INSERT INTO Users (username, name) VALUES ('sayalipandav30', 'Sayali Pandav');
INSERT INTO Users (username, name) VALUES ('Sayam417', 'Sayam Hirachand Padmannavar');
INSERT INTO Users (username, name) VALUES ('tejaswiseelam', 'Seelam Tejaswi');
INSERT INTO Users (username, name) VALUES ('shan_Thakur', 'Shan Thakur');
INSERT INTO Users (username, name) VALUES ('sharadkumar22', 'Sharad Kumar');
INSERT INTO Users (username, name) VALUES ('Sharanmalali', 'Sharan Malali');
INSERT INTO Users (username, name) VALUES ('8JyMhCJeYb', 'Sharanabasappa Biradar');
INSERT INTO Users (username, name) VALUES ('sharmila_devi_pk', 'SHARMILA DEVI PK');
INSERT INTO Users (username, name) VALUES ('Sharvani_G', 'Sharvani G Bhaskar');
INSERT INTO Users (username, name) VALUES ('Sharvesh_Babu', 'Sharvesh Babu J M');
INSERT INTO Users (username, name) VALUES ('ShashwatD_510', 'Shashwat D');
INSERT INTO Users (username, name) VALUES ('colonel_', 'Shashwat Ranjan');
INSERT INTO Users (username, name) VALUES ('Shaurya_jha', 'Shaurya Jha');
INSERT INTO Users (username, name) VALUES ('HI_SHILPA', 'Shilpa Kumari');
INSERT INTO Users (username, name) VALUES ('Shinchana2005', 'Shinchana R Reddy');
INSERT INTO Users (username, name) VALUES ('DelightCoder', 'shiv');
INSERT INTO Users (username, name) VALUES ('shivani_shree', 'Shivani Shree S');
INSERT INTO Users (username, name) VALUES ('Shobhit_Gupta_', 'Shobhit Gupta');
INSERT INTO Users (username, name) VALUES ('shraddhaawaradi09', 'Shraddha awaradi');
INSERT INTO Users (username, name) VALUES ('Shraddha R Patil', 'Shraddha R Patil');
INSERT INTO Users (username, name) VALUES ('Shravan_vathsa', 'Shravan Shreevathsa C');
INSERT INTO Users (username, name) VALUES ('Shravya-', 'Shravya R Hegde');
INSERT INTO Users (username, name) VALUES ('shree_dhanya', 'Shree Dhanya Sagar');
INSERT INTO Users (username, name) VALUES ('shreenisha', 'shreenisha S');
INSERT INTO Users (username, name) VALUES ('Shreyacode11', 'Shreya B Saboji');
INSERT INTO Users (username, name) VALUES ('Shreya115', 'Shreya P');
INSERT INTO Users (username, name) VALUES ('shreyansh_agr30', 'Shreyansh Agrawal');
INSERT INTO Users (username, name) VALUES ('mahi_rocks', 'SHREYANSH KUMAR SINGH');
INSERT INTO Users (username, name) VALUES ('Rex0', 'Shreyas kage');
INSERT INTO Users (username, name) VALUES ('ShreyasDure', 'Shreyas Ramchandra Dure');
INSERT INTO Users (username, name) VALUES ('shreyass44', 'Shreyas S');
INSERT INTO Users (username, name) VALUES ('shreyash_shaurya', 'Shreyash Shaurya');
INSERT INTO Users (username, name) VALUES ('nazu001', 'Shrihari Viswanathan');
INSERT INTO Users (username, name) VALUES ('Shrinath_Venkatesh', 'Shrinath Venkatesh');
INSERT INTO Users (username, name) VALUES ('shree7b0', 'Shriraj Chaitanya Bhargave');
INSERT INTO Users (username, name) VALUES ('Varun2325', 'Shriyans Nayak');
INSERT INTO Users (username, name) VALUES ('Shrutika Manwatkar', 'Shrutika Manwatkar');
INSERT INTO Users (username, name) VALUES ('shubhamk2005', 'Shubham Karkhanis');
INSERT INTO Users (username, name) VALUES ('khatrishu2q80', 'Shubham Khatri');
INSERT INTO Users (username, name) VALUES ('Dancefun321', 'Shubhan CD');
INSERT INTO Users (username, name) VALUES ('shwetaaa_1309', 'Shweta A');
INSERT INTO Users (username, name) VALUES ('Shyample_code', 'Shyam S Annigeri');
INSERT INTO Users (username, name) VALUES ('SRamanjaneyulu', 'SIDDAMSETTY RAMAJANEYULU');
INSERT INTO Users (username, name) VALUES ('sidsidu', 'Siddhanth Narendra Kuthnikar');
INSERT INTO Users (username, name) VALUES ('sid2x24', 'Siddharth Mishra');
INSERT INTO Users (username, name) VALUES ('siddhartha_singhal02', 'Siddhartha singhal');
INSERT INTO Users (username, name) VALUES ('Tripathi_sid', 'Sidhant Tripathi');
INSERT INTO Users (username, name) VALUES ('1Simran', 'SIMRAN PATHAK');
INSERT INTO Users (username, name) VALUES ('_Sinchana_02', 'Sinchana');
INSERT INTO Users (username, name) VALUES ('sinch_2007', 'Sinchana Haritsa');
INSERT INTO Users (username, name) VALUES ('_Sinchana06', 'Sinchana Shankar');
INSERT INTO Users (username, name) VALUES ('Sinchana_S_Gujjar', 'Sinchana Sunil Kumar Gujjar');
INSERT INTO Users (username, name) VALUES ('Sinchana.R', 'Sinchana.R');
INSERT INTO Users (username, name) VALUES ('Sindhu_Harakangi100', 'Sindhu harakangi');
INSERT INTO Users (username, name) VALUES ('Sivarathna22', 'SIVA RATHNA SRI V');
INSERT INTO Users (username, name) VALUES ('Sivakarthikeyan_M', 'Sivakarthikeyan M');
INSERT INTO Users (username, name) VALUES ('sivunisrefg4r', 'sivuni sreeraga');
INSERT INTO Users (username, name) VALUES ('siyapatil04', 'Siya Patil');
INSERT INTO Users (username, name) VALUES ('Viswaja06', 'SK.VISWAJA');
INSERT INTO Users (username, name) VALUES ('Smaya_S_M', 'Smaya Sadanand Maben');
INSERT INTO Users (username, name) VALUES ('Sneha20_', 'Sneha L');
INSERT INTO Users (username, name) VALUES ('Snehask09', 'Sneha S Khatawakar');
INSERT INTO Users (username, name) VALUES ('SnehaN02', 'Sneha.N');
INSERT INTO Users (username, name) VALUES ('Sohan_g_123', 'Sohan G');
INSERT INTO Users (username, name) VALUES ('sohankalburgi2004', 'Sohan K E');
INSERT INTO Users (username, name) VALUES ('somu__', 'Someshwar G');
INSERT INTO Users (username, name) VALUES ('soumyadip04', 'Soumyadip Chakraborty');
INSERT INTO Users (username, name) VALUES ('soundararunachalam3639', 'Soundar Arunachalam R M');
INSERT INTO Users (username, name) VALUES ('sourabhaprasad', 'Sourabha K H');
INSERT INTO Users (username, name) VALUES ('SpandanaHS', 'Spandana H.S');
INSERT INTO Users (username, name) VALUES ('Spandana_7', 'Spandana R');
INSERT INTO Users (username, name) VALUES ('SparshAgrawal123', 'Sparsh Agrawal');
INSERT INTO Users (username, name) VALUES ('Sragvi_1001', 'Sragvi Jaisimha');
INSERT INTO Users (username, name) VALUES ('SrajanKumar0', 'Srajan');
INSERT INTO Users (username, name) VALUES ('sreejeeta', 'Sreejeeta Roy');
INSERT INTO Users (username, name) VALUES ('sreeramvishnu_t1', 'Sreeram Vishnu');
INSERT INTO Users (username, name) VALUES ('Sri_Sowmi06', 'Sri Sowmi K P');
INSERT INTO Users (username, name) VALUES ('Sri-Venkata', 'Sri Venkata');
INSERT INTO Users (username, name) VALUES ('Sridatta.m', 'Sridatta M');
INSERT INTO Users (username, name) VALUES ('SHREE_SASI', 'SRINITHI P');
INSERT INTO Users (username, name) VALUES ('Srinivas-D-A', 'Srinivas D A');
INSERT INTO Users (username, name) VALUES ('srishti__04', 'Srishti Ranjan');
INSERT INTO Users (username, name) VALUES ('srujana_2704', 'Srujana A Rao');
INSERT INTO Users (username, name) VALUES ('Srujana', 'Srujana.C.A');
INSERT INTO Users (username, name) VALUES ('srushthi_sb013', 'srushti siddalingappa biradar');
INSERT INTO Users (username, name) VALUES ('Sruthialamelu', 'Sruthi Alamelu S');
INSERT INTO Users (username, name) VALUES ('Therealsteve', 'Steve Solomon J');
INSERT INTO Users (username, name) VALUES ('Sucharitha_N', 'Sucharitha N');
INSERT INTO Users (username, name) VALUES ('sudarshan_ps', 'Sudarshan PS');
INSERT INTO Users (username, name) VALUES ('deepusudeep18', 'Sudeep S Rajpurohit');
INSERT INTO Users (username, name) VALUES ('namerror', 'Sudhanshu Raj');
INSERT INTO Users (username, name) VALUES ('sportchamp2006', 'Sudhanva S M');
INSERT INTO Users (username, name) VALUES ('kousersufiya20', 'sufiya kouser');
INSERT INTO Users (username, name) VALUES ('Suganya-G', 'Suganya G');
INSERT INTO Users (username, name) VALUES ('SUJA_SUNDARAM', 'SUJA S');
INSERT INTO Users (username, name) VALUES ('Sujai_Raj_727', 'Sujai Raj S');
INSERT INTO Users (username, name) VALUES ('suiiiiijal', 'Sujal Yadav');
INSERT INTO Users (username, name) VALUES ('sukesh_ns', 'SUKESH N S');
INSERT INTO Users (username, name) VALUES ('sumant4879', 'Sumant kulkarni');
INSERT INTO Users (username, name) VALUES ('sumanthd032', 'Sumantha');
INSERT INTO Users (username, name) VALUES ('boron_', 'Sumedh Singh Virk');
INSERT INTO Users (username, name) VALUES ('sumukh_bhargav', 'Sumukh Bhargav .Y.');
INSERT INTO Users (username, name) VALUES ('sundaresh1311', 'Sundaresh A M');
INSERT INTO Users (username, name) VALUES ('SupraD', 'Supraja D');
INSERT INTO Users (username, name) VALUES ('suprajavrao', 'Supraja V Rao');
INSERT INTO Users (username, name) VALUES ('SURYA_175', 'SURYA S');
INSERT INTO Users (username, name) VALUES ('SURYATEJS', 'Surya Tej S');
INSERT INTO Users (username, name) VALUES ('SURYANSH1747', 'SURYANSH JHA');
INSERT INTO Users (username, name) VALUES ('suryanshshaahi', 'suryansh shahi');
INSERT INTO Users (username, name) VALUES ('sushanth-rai', 'Sushanth Rai');
INSERT INTO Users (username, name) VALUES ('_sushanths_', 'Sushanth S');
INSERT INTO Users (username, name) VALUES ('sushma_c45', 'Sushma');
INSERT INTO Users (username, name) VALUES ('sushmithamg_cs24', 'Sushmitha M G');
INSERT INTO Users (username, name) VALUES ('_suyash_', 'Suyash Mishra');
INSERT INTO Users (username, name) VALUES ('Aquaclasher_og', 'Swapnil Patidar');
INSERT INTO Users (username, name) VALUES ('swatibastawade', 'Swati');
INSERT INTO Users (username, name) VALUES ('Syedayaan_07', 'Syed ayaan');
INSERT INTO Users (username, name) VALUES ('syedalm263', 'syeda almas');
INSERT INTO Users (username, name) VALUES ('mahin2409', 'Syeda Noor Mahin');
INSERT INTO Users (username, name) VALUES ('gowthamjigans6', 'T.Gowtham jignas');
INSERT INTO Users (username, name) VALUES ('Tanish21', 'Tanish R Magaji');
INSERT INTO Users (username, name) VALUES ('tanny-96', 'Tanishq Jaitapurkar');
INSERT INTO Users (username, name) VALUES ('ubrmensch', 'Tanmay');
INSERT INTO Users (username, name) VALUES ('TANMAY-G-PROG', 'Tanmaya G Shetty');
INSERT INTO Users (username, name) VALUES ('tp_cse25', 'Tanya Pandey');
INSERT INTO Users (username, name) VALUES ('srikavya_57', 'Tarigopula Srikavya');
INSERT INTO Users (username, name) VALUES ('Tejas_Bhimani', 'Tejas Bhimani');
INSERT INTO Users (username, name) VALUES ('Tejascm', 'Tejas C M');
INSERT INTO Users (username, name) VALUES ('Tejas Gowda', 'Tejas Gowda S');
INSERT INTO Users (username, name) VALUES ('tejastm75job', 'Tejas T M');
INSERT INTO Users (username, name) VALUES ('Tejashwinikoppal', 'Tejashwini');
INSERT INTO Users (username, name) VALUES ('TejaswiniN29', 'Tejaswini N');
INSERT INTO Users (username, name) VALUES ('lazygalaxy', 'Tejaswini P');
INSERT INTO Users (username, name) VALUES ('Thanga_Vignesh_M', 'Thanga Vignesh M');
INSERT INTO Users (username, name) VALUES ('Tharun_BR', 'Tharun BR');
INSERT INTO Users (username, name) VALUES ('thijesh_praveen_28', 'THIJESH PRAVEEN V');
INSERT INTO Users (username, name) VALUES ('Thilak_17', 'Thilak H M');
INSERT INTO Users (username, name) VALUES ('TJ_2712', 'Tirth Jain');
INSERT INTO Users (username, name) VALUES ('trish306', 'Trishala Kalasapura Arun');
INSERT INTO Users (username, name) VALUES ('uday_12345ai', 'Uday Kumar M');
INSERT INTO Users (username, name) VALUES ('UdbhaviShetty', 'Udbhavi U Shetty');
INSERT INTO Users (username, name) VALUES ('ullas_n', 'Ullas N');
INSERT INTO Users (username, name) VALUES ('urjasrivau670', 'Urja Srivastava');
INSERT INTO Users (username, name) VALUES ('ur-ka-shi', 'Urvashi Sheshrao Kamble');
INSERT INTO Users (username, name) VALUES ('Usha_Rani_00', 'UshaRani');
INSERT INTO Users (username, name) VALUES ('balaji1301', 'V BALAJI');
INSERT INTO Users (username, name) VALUES ('PunishingPoison', 'V C Mohit Rao');
INSERT INTO Users (username, name) VALUES ('kiran813', 'V S Kiran');
INSERT INTO Users (username, name) VALUES ('soundharyavenkat', 'V SOUNDHARYA LAKSHMI');
INSERT INTO Users (username, name) VALUES ('vachana_mh', 'Vachana M H');
INSERT INTO Users (username, name) VALUES ('Vadiraj nadig', 'Vadiraj P Nadig');
INSERT INTO Users (username, name) VALUES ('vaibhav010606', 'Vaibhav');
INSERT INTO Users (username, name) VALUES ('vaibhav027', 'Vaibhav Kumar');
INSERT INTO Users (username, name) VALUES ('Vaibhav-18', 'Vaibhav shanbhag');
INSERT INTO Users (username, name) VALUES ('vaibraksh', 'Vaibhavi J Hiremath');
INSERT INTO Users (username, name) VALUES ('Vaibhavijadhav', 'Vaibhavi Jadhav');
INSERT INTO Users (username, name) VALUES ('Vaishnavee_7', 'Vaishnavee Chaurasia');
INSERT INTO Users (username, name) VALUES ('vaishnavi__bharadwaj', 'Vaishnavi R Bharadwaj');
INSERT INTO Users (username, name) VALUES ('Vaishnavi_Ravi_Bhoyi', 'Vaishnavi Ravi Bhoyi');
INSERT INTO Users (username, name) VALUES ('vallumadhu', 'Vallu Madhu');
INSERT INTO Users (username, name) VALUES ('Vandana G Kanvihalli', 'Vandana');
INSERT INTO Users (username, name) VALUES ('Vandana', 'Vandana G Kanvihalli');
INSERT INTO Users (username, name) VALUES ('vanessa_ds', 'Vanessa DSouza');
INSERT INTO Users (username, name) VALUES ('Varada_Ritika', 'Varada Ritika');
INSERT INTO Users (username, name) VALUES ('varsha_bannatti', 'varsha vb');
INSERT INTO Users (username, name) VALUES ('varshiez', 'Varshini');
INSERT INTO Users (username, name) VALUES ('Varshini_D6', 'VARSHINI D');
INSERT INTO Users (username, name) VALUES ('MVARSH', 'VARSHINI M');
INSERT INTO Users (username, name) VALUES ('varshinis4', 'VARSHINI S');
INSERT INTO Users (username, name) VALUES ('Varshiitha', 'Varshitha');
INSERT INTO Users (username, name) VALUES ('varshitha2708', 'Varshitha G');
INSERT INTO Users (username, name) VALUES ('NA', 'Varun.P');
INSERT INTO Users (username, name) VALUES ('vveda_2006', 'Veda Varshini');
INSERT INTO Users (username, name) VALUES ('vedanthavinay_c1', 'Vedantha Vinay Vernekar');
INSERT INTO Users (username, name) VALUES ('maxandmaximum', 'veeresh');
INSERT INTO Users (username, name) VALUES ('Venkatesh', 'Venkatesh');
INSERT INTO Users (username, name) VALUES ('Vennila_P_696', 'VENNILA P');
INSERT INTO Users (username, name) VALUES ('Vismitha', 'Viamitha.H.N');
INSERT INTO Users (username, name) VALUES ('vidyahtazu', 'Vidya H R');
INSERT INTO Users (username, name) VALUES ('MrVk_27', 'Vignesh K');
INSERT INTO Users (username, name) VALUES ('Vijai_V_S', 'Vijai V S');
INSERT INTO Users (username, name) VALUES ('vijayshy3bxr', 'Vijay Shyam');
INSERT INTO Users (username, name) VALUES ('vikhyaathh_', 'Vikhyaath M');
INSERT INTO Users (username, name) VALUES ('mrvickyvp', 'vikki pawar');
INSERT INTO Users (username, name) VALUES ('vinay2kumar2025', 'Vinay kumar');
INSERT INTO Users (username, name) VALUES ('vinayreddy765', 'Vinay Reddy');
INSERT INTO Users (username, name) VALUES ('Vinay_s_p_12', 'VINAY S P');
INSERT INTO Users (username, name) VALUES ('vinayasri_07', 'VINAYA SRI MADADI');
INSERT INTO Users (username, name) VALUES ('vinayakrb', 'Vinayak R B');
INSERT INTO Users (username, name) VALUES ('vinothkumarg1', 'Vinothkumar G');
INSERT INTO Users (username, name) VALUES ('Vinuta_J_H', 'Vinuta J H');
INSERT INTO Users (username, name) VALUES ('vipulreddy15', 'VIPUL REDDY GUNDALU');
INSERT INTO Users (username, name) VALUES ('ViratM', 'Virat Malviya');
INSERT INTO Users (username, name) VALUES ('visaka_vel14.', 'Visaka P');
INSERT INTO Users (username, name) VALUES ('Vishal Kale', 'Vishal Kale');
INSERT INTO Users (username, name) VALUES ('vishal27-', 'Vishal V Magadi');
INSERT INTO Users (username, name) VALUES ('VISHNUBPRIYAA', 'Vishnub Priya A');
INSERT INTO Users (username, name) VALUES ('vishruth510', 'Vishruth Vijay Kumar');
INSERT INTO Users (username, name) VALUES ('Vishrutha333', 'Vishrutha Bangle');
INSERT INTO Users (username, name) VALUES ('VishruthaShekar', 'Vishrutha Shekar');
INSERT INTO Users (username, name) VALUES ('_Astillite', 'Vishwa H');
INSERT INTO Users (username, name) VALUES ('@vishwaavetri', 'VISHWAA V T');
INSERT INTO Users (username, name) VALUES ('vishwajeet009', 'Vishwajeet Singh Sajwan');
INSERT INTO Users (username, name) VALUES ('VTG56', 'Vishwaradhya S Aiholli');
INSERT INTO Users (username, name) VALUES ('Vismitha H.N', 'Vismitha.H.N');
INSERT INTO Users (username, name) VALUES ('dammit_boy', 'VIVIN JAYANTH NM');
INSERT INTO Users (username, name) VALUES ('VDXG2006', 'Vrishin Dutt');
INSERT INTO Users (username, name) VALUES ('davidcarey_97', 'William Carey J');
INSERT INTO Users (username, name) VALUES ('yashdhadge', 'Yash Dhadge');
INSERT INTO Users (username, name) VALUES ('Kid-ye', 'Yash Gupta');
INSERT INTO Users (username, name) VALUES ('Pratham_2502', 'Yash Shrivastava');
INSERT INTO Users (username, name) VALUES ('Yasha_Balaji', 'Yasha Balaji');
INSERT INTO Users (username, name) VALUES ('_Yashas_P_', 'Yashas P');
INSERT INTO Users (username, name) VALUES ('Z9dmgBKiZG', 'YASHASVI BEESAM');
INSERT INTO Users (username, name) VALUES ('yashmakra', 'Yashdeep');
INSERT INTO Users (username, name) VALUES ('Yashika S', 'Yashika S');
INSERT INTO Users (username, name) VALUES ('Yashitha_V', 'Yashitha V');
INSERT INTO Users (username, name) VALUES ('Yashwanth C', 'Yashwanth C');
INSERT INTO Users (username, name) VALUES ('yashwanthpv20', 'Yashwanth.P');
INSERT INTO Users (username, name) VALUES ('yasmeen51', 'Yasmeen R');
INSERT INTO Users (username, name) VALUES ('yaswanth1807', 'YASWANTH BALAJI S');
INSERT INTO Users (username, name) VALUES ('00_Escape_00', 'Yatharth Gupta');
INSERT INTO Users (username, name) VALUES ('yeshwini_01', 'Yeshwini Gupta.L');
INSERT INTO Users (username, name) VALUES ('Yogesh_18_B', 'Yogesh B');
INSERT INTO Users (username, name) VALUES ('yogeshfulari2004', 'YOGESH FULARI');
INSERT INTO Users (username, name) VALUES ('YogitaNaik', 'Yogita Babu Naik');
INSERT INTO Users (username, name) VALUES ('Yogitha R Reddy', 'Yogitha R Reddy');
INSERT INTO Users (username, name) VALUES ('Yohitha_Reddy', 'Yohitha Reddy');
INSERT INTO Users (username, name) VALUES ('yukthirknova', 'Yukthi R K');
INSERT INTO Users (username, name) VALUES ('zameernagaral', 'Zameer Abdulkalam Nagaral');
INSERT INTO Users (username, name) VALUES ('aprameyaarao', 'Aprameya A Rao');
INSERT INTO Users (username, name) VALUES ('Hrithik875','Hrithik');


INSERT INTO Problems (question_name, points, link, day, isPublic, solution_link, isSolutionPublic) VALUES ('Fizz Buzz', 10, 'https://leetcode.com/problems/fizz-buzz/description/', 1, 0, NULL, 0);
INSERT INTO Problems (question_name, points, link, day, isPublic, solution_link, isSolutionPublic) VALUES ('Happy Number', 10, 'https://leetcode.com/problems/happy-number/description/', 1, 0, NULL, 0);
INSERT INTO Problems (question_name, points, link, day, isPublic, solution_link, isSolutionPublic) VALUES ('Reverse Integer', 10, 'https://leetcode.com/problems/reverse-integer/description/', 1, 0, NULL, 0);
INSERT INTO Problems (question_name, points, link, day, isPublic, solution_link, isSolutionPublic) VALUES ('Palindrome Number', 10, 'https://leetcode.com/problems/palindrome-number/', 2, 0, NULL, 0);
INSERT INTO Problems (question_name, points, link, day, isPublic, solution_link, isSolutionPublic) VALUES ('Find Factorial', 10, 'https://leetcode.com/problems/clumsy-factorial/description/', 2, 0, NULL, 0);
INSERT INTO Problems (question_name, points, link, day, isPublic, solution_link, isSolutionPublic) VALUES ('Generate Fibonacci Sequence', 10, 'https://leetcode.com/problems/generate-fibonacci-sequence/', 2, 0, NULL, 0);


INSERT INTO Leaderboard (username, points, streak) 
SELECT username, 0, 0 FROM Users;